version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_KEY_VAULT_NAME=ToKaKeyVault
    volumes:
      - ./api:/api
    depends_on:
      - frontend

  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
