version: '3.8'

services:
  backend:
    build:
      context: ./api
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    environment:
      - AZURE_KEY_VAULT_NAME=ToKaKeyVault
    volumes:
      - ./api:/api

  frontend:
    build:
      context: ./front-end-nextjs
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    depends_on:
    - backend
    volumes:
      - ./front-end-nextjs:/front-end-nextjs