FROM node:18

WORKDIR /app

#copy dependencies
COPY package*.json ./

RUN npm install

#copy rest of the files
COPY . .

ARG NEXT_PUBLIC_API_URL
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL

RUN npm run build

EXPOSE 3000

#run the application
CMD ["npm", "start"]

